spring:
  datasource:
    url: 'jdbc:mysql://mariadb:3306/hapi'
    username: admin
    password: $DB_PASS
    driverClassName: com.mysql.cj.jdbc.Driver
    max-active: 15

    # database connection pool size
    hikari:
      maximum-pool-size: 10
  batch:
    job:
      enabled: false

hapi:
  fhir:
    fhir_version: R4
    supported_resource_types: #must come before IG, otherwise is ignored
      - Patient
      - Observation
      - StructureDefinition
      - ValueSet
      - CodeSystem
      - NamingSystem
      - Bundle
      - CarePlan
      - Condition
      - Encounter
      - Goal
      - Subscription
      - Binary
      - MedicationKnowledge
    implementationguides:
#      - url: https://build.fhir.org/ig/HL7/fhir-ips/package.tgz
#        name: hl7.fhir.uv.ips
#        version: 1.0.0
      - url: https://joofio.github.io/medicationIG/package.tgz
        name: medication.ig.example
        version: 0.1.0
    server_address: http://18.193.162.67/

    enable_repository_validating_interceptor: true


    allow_contains_searches: true
    allow_external_references: true
    default_encoding: JSON
    default_pretty_print: true
    default_page_size: 20
    client_id_strategy: ALPHANUMERIC
    filter_search_enabled: true
    narrative_enabled: true
    cors:
      allow_Credentials: true
      # These are allowed_origin patterns, see: https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/web/cors/CorsConfiguration.html#setAllowedOriginPatterns-java.util.List-
      allowed_origin:
        - '*'

    # Search coordinator thread pool sizes
    search-coord-core-pool-size: 20
    search-coord-max-pool-size: 100
    search-coord-queue-capacity: 200
    tester:
      home:
        name: Local Tester
        server_address: "http://18.193.162.67/fhir"
        refuse_to_fetch_third_party_urls: false
        fhir_version: R4

      global:
        name: Global Tester
        server_address: "http://hapi.fhir.org/baseR4"
        refuse_to_fetch_third_party_urls: false
        fhir_version: R4
