version: '3.7'
services:
  fhir-server:
    image: "hapiproject/hapi:latest"
    ports:
      - "8080:8080"
    volumes:
     - .:/data/hapi
    environment:
     SPRING_CONFIG_LOCATION: 'https://raw.githubusercontent.com/joofio/my-hapi-fhir/main/kl.yml'
      #      hapi.fhir.default_encoding: "json" 
    depends_on:
        - mariadb
  mariadb:
    image: mariadb:latest
    container_name: mariadb
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci  --lower_case_table_names=1
    volumes:
    - ./data/mysql:/var/lib/mysql
    - ./mariadbconf:/etc/mysql/conf.d
    environment:
    - MYSQL_DATABASE=hapi
    - MYSQL_ROOT_PASSWORD=admin
    - MYSQL_USER=admin
    - MYSQL_PASSWORD=admin
    ports:
    - "3306:3306"
