version: '3.7'
services:
  web:
    image: "hapiproject/hapi:v5.3.0"
    ports:
      - "8080:8080"
    volumes:
     - /mnt/c/Users/joaof/Desktop/docker:/data/hapi
    environment:
     SPRING_CONFIG_LOCATION: 'file:////data/hapi/kl.yml'
      #      hapi.fhir.default_encoding: "json" 
    depends_on:
        - mariadb
  mariadb:
    image: mariadb:latest
    container_name: mariadb
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
    - /home/$USER/data/mysql:/var/lib/mysql
    environment:
    - MYSQL_DATABASE=hapi_r4
    - MYSQL_ROOT_PASSWORD=admin
    - MYSQL_USER=admin
    - MYSQL_PASSWORD=admin
    ports:
    - 3306:3306
