spring:
  datasource:
    url: 'jdbc:mysql://mariadb:3306/hapi'
    username: admin
    password: admin
    driverClassName: com.mysql.cj.jdbc.Driver
    max-active: 15


  batch:
    job:
      enabled: false

hapi:
  fhir:
    fhir_version: R4
    supported_resource_types:
      - Patient
      - Observation
      - StructureDefinition
      - ValueSet
      - CodeSystem
      - NamingSystem
      - Bundle
      - CarePlan
      - Condition
      - Encounter
      - Goal
      - Binary
      - Subscription
      - Practitioner
      - Substance
      - MedicinalProduct
      - Coverage
      - Appointment
      - Slot
      - Schedule
      - Organization
      - Person
      - MedicationRequest
      - Medication
      - MedicationKnowledge
      - Procedure
    implementationguides:
      - url: http://build.fhir.org/ig/hl7-be/riziv-medication-record/package.tgz
        name: hl7.fhir.be.riziv-medicationrecord
        version: 0.1.0-test

    enable_repository_validating_interceptor: true



    allow_contains_searches: true
    allow_external_references: true
    default_encoding: JSON
    default_pretty_print: true
    default_page_size: 20
    client_id_strategy: ALPHANUMERIC
    filter_search_enabled: true
    narrative_enabled: true
    cors:
      allow_Credentials: true
      # These are allowed_origin patterns, see: https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/web/cors/CorsConfiguration.html#setAllowedOriginPatterns-java.util.List-
      allowed_origin:
        - '*'

    # Search coordinator thread pool sizes
    search-coord-core-pool-size: 20
    search-coord-max-pool-size: 100
    search-coord-queue-capacity: 200
    tester:
      home:
        name: Local Tester
        server_address: "http://localhost:8080/fhir"
        refuse_to_fetch_third_party_urls: false
        fhir_version: R4

      global:
        name: Global Tester
        server_address: "http://hapi.fhir.org/baseR4"
        refuse_to_fetch_third_party_urls: false
        fhir_version: R4
