#matchbox:
#  resolve:
#    baseurl: http://hapi.fhir.org/baseR4
#
#hapi:
#  fhir:
#    server:
#      path: /r4/*
#    rest:
#      server-name: matchbox ahdis         
#    implementationguides:
#      -
#       name: hl7.fhir.pubpack
#       version: 0.0.7
#      -
#       name: hl7.fhir.xver-extensions
#       version: 0.0.5
#         name: hl7.terminology.r4
#       version: 2.0.0
#      -
#        name: ch.fhir.ig.ch-epr-term
#        version: 2.0.5
#      -
#        name: ch.fhir.ig.ch-core
#        version: 2.0.0
#      -
#        name: ch.fhir.ig.ch-vacd
#        version: 1.0.0
#      -
#        name: ch.fhir.ig.ch-emed
#        version: 1.0.0
#      -
#        name: ch.fhir.ig.ch-atc
#        version: 3.1.0
#      -
#        name: hl7.fhir.uv.sdc
#        version: 2.7.0
#      -
#        name: ch.fhir.ig.ch-orf
#        version: 0.10.0
#      -
#        name: ch.fhir.ig.ch-rad-order
#        version: 0.1.0
#      -
#        name: ch.fhir.ig.ch-etoc
#        version: 0.1.0
#      -
#        name: ihe.mhd.fhir
#        version: 4.0.1
#      -
#        name: ch.fhir.ig.ch-epr-mhealth
#        version: 0.2.0
#      -
#        name: hl7.fhir.cda
#        version: dev
#      -
#        name: ch.fhir.ig.cda-fhir-maps
#        version: 0.2.0
#server:
#  port: 8080


matchbox:
  resolve:
    baseurl: http://hapi.fhir.org/baseR4

spring:
  datasource:
    #url: 'jdbc:h2:mem:test_mem'
    url: "jdbc:h2:file:./target/database/h2"
    username: sa
    password: null
    driverClassName: org.h2.Driver
    max-active: 15
  batch:
    job:
      enabled: false

hapi:
  fhir:
    fhir_version: R4
    implementationguides:
      - url: http://build.fhir.org/ig/hl7dk/kl-gateway/branches/remove-slicing-from-entry/package.tgz
        name: hl7.fhir.dk.kl.gateway.care
        version: 1.0
      -
       name: hl7.fhir.pubpack
       version: 0.0.7
      -
       name: hl7.fhir.xver-extensions
       version: 0.0.5
      -  
       name: hl7.terminology.r4
       version: 2.0.0
      -
       name: ch.fhir.ig.ch-epr-term
       version: 2.0.5
      -
       name: ch.fhir.ig.ch-core
       version: 2.0.0
      -
       name: ch.fhir.ig.ch-vacd
       version: 1.0.0
      -
       name: ch.fhir.ig.ch-emed
       version: 1.0.0
      -
       name: ch.fhir.ig.ch-atc
       version: 3.1.0
      -
       name: hl7.fhir.uv.sdc
       version: 2.7.0
      -
       name: ch.fhir.ig.ch-orf
       version: 0.10.0
      -
       name: ch.fhir.ig.ch-rad-order
       version: 0.1.0
      -
       name: ch.fhir.ig.ch-etoc
       version: 0.1.0
      -
       name: ihe.mhd.fhir
       version: 4.0.1
      -
       name: ch.fhir.ig.ch-epr-mhealth
       version: 0.2.0
      -
       name: hl7.fhir.cda
       version: dev
      -
       name: ch.fhir.ig.cda-fhir-maps
       version: 0.2.0
    enable_repository_validating_interceptor: true

    supported_resource_types:
      - Patient
      - Observation
      - StructureDefinition
      - ValueSet
      - CodeSystem
      - NamingSystem
      - Bundle
      - CarePlan
      - Condition
      - Encounter
      - Goal
      - Binary
      - Subscription
      - Practitioner
      - Substance
      - MedicinalProduct
      - Coverage
      - Appointment
      - Slot
      - Schedule
      - Organization
      - Person
      - MedicationRequest
      - Medication
      - MedicationKnowledge
      - Procedure

    allow_contains_searches: true
    allow_external_references: true
    default_encoding: JSON
    default_pretty_print: true
    default_page_size: 20
    client_id_strategy: ALPHANUMERIC
    filter_search_enabled: true
    narrative_enabled: true
    cors:
      allow_Credentials: true
      # These are allowed_origin patterns, see: https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/web/cors/CorsConfiguration.html#setAllowedOriginPatterns-java.util.List-
      allowed_origin:
        - '*'

    # Search coordinator thread pool sizes
    search-coord-core-pool-size: 20
    search-coord-max-pool-size: 100
    search-coord-queue-capacity: 200
    tester:
      home:
        name: Local Tester
        server_address: "http://localhost:8080/fhir"
        refuse_to_fetch_third_party_urls: false
        fhir_version: R4

      global:
        name: Global Tester
        server_address: "http://hapi.fhir.org/baseR4"
        refuse_to_fetch_third_party_urls: false
        fhir_version: R4